services:
  minecraft-server:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.21.8"
      MEMORY: "16384M"
      MOTD: "Список геев: Альберт, Максим, Константин, Юрий, Никита, Марат, Андрей, Илья, Шамиль\\nПоебаться с другом это круто!"
      ONLINE_MODE: "false"
      DIFFICULTY: "2"
      LEVEL: "Мужская сосисочная"
    volumes:
      - "./data:/data"
      - "./mods:/mods"